# Generated by Django 5.0.3 on 2024-05-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagese', '0002_message_delete_messege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
