# Generated by Django 5.0.3 on 2024-05-16 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagese', '0005_alter_friendslist_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
